title: Widyah Kurniasari # your name (or website title) here
logo: "(https://user-images.githubusercontent.com/104265063/165008568-698f00e2-e8b0-4b11-8c95-e141694f953c.jpeg)" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<br>
 (PZSIB) Data Warehousing, Visualization, and Analysis for Bussines Insight in Zenius 
  <br>
  Statistics Student Undergraduate at Diponegoro University 
  <br>
  Semarang, Central Java, Indonesia
  <br><br>
  <a href="https://www.instagram.com/widyah.kur/">View My Instagram Profile </a> 
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID her

